language: node_js, ruby
node_js:
  - "4.1"
rvm: 2.1

script: galen check galen-test/home.gspec --url _site/blogTestGalen/ --size 1024x768 --htmlreport reports

before_install:
    - gem install jekyll
    - jekyll build
    - npm install
    - npm install -g galenframework-cli
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start

notifications:
  slack:
    on_success: never
    on_failure: never
