language: node_js, ruby
node_js:
  - "4.1"
rvm: 2.1

travis console

cache:
  directories :
    - node_modules
    - bundler

notifications:
  email:
    on_success: never
    on_failure: never
    email: false
