language: node_js
node_js:
  - "4.1"
sudo: required

before_install:
  - rvm install 2.1.5
#  - npm install
  - npm install -g galenframework-cli
  - sudo apt-get install html2text
#  - sudo aptitude install w3m
  - sudo apt-get install w3m
#  - gem install jekyll
# - jekyll serve &

cache:
  directories:
    - node_modules
    - bundler

notifications:
    email: false

# whitelist
branches:
  only:
    - master
    - gh-pages


before_script:
  - cp ./tests/content/ ./ -r
#  - jekyll build
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
#  - sleep 5 # give xvfb some time to start

script:
#  - ./node_modules/karma/bin/karma start karma.conf.js
#  - htmlproof ./_site --verbose --href-ignore "#" --disable-external --file-ignore './_site/node_modules/*'
#  - jekyll serve &
   - sleep 1 # give jekyll some time to start
   - galen test tests/galen/all.test --htmlreport tests/galen/reports/all
   - w3m -dump tests/galen/reports/all/report.html | less & sleep 12
#  - galen test ./tests/galen/blog/menu/header-menu-mobile.js --htmlreport tests/galen/reports/behavior

after_script:
  - w3m -dump tests/galen/reports/all/report.html | less & sleep 10
#  - less tests/galen/reports/all/report.html & sleep 1
#  - less tests/galen/reports/all/report.json & sleep 1
  - rake travis:deploy --trace --verbose
