language: node_js
node_js:
  - "4.1"

"scripts": {
    "test": "grunt travis --verbose"
  }

before_install:
  - npm install
  - npm install -g galenframework-cli
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

