language: node_js
node_js:
  - "4.1"

script: galen check galen-test/home.gspec --url http://127.0.0.1:4000/ --size 1024x768 --htmlreport reports

before_install:
    - npm install jekyll
    - jekyll serve
    - npm install
    - npm install -g galenframework-cli
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start



