language: node_js
node_js:
  - "4.1"

before_install:
  - rvm install 2.1.5
  - npm install
  - npm install -g galenframework-cli
  - gem install jekyll
# - jekyll serve &

cache:
  directories:
    - node_modules
    - bundler

notifications:
    email: false

# whitelist
branches:
  only:
    - master
    - gh-pages


before_script:
  - cp ./tests/content/ ./ -r
  - jekyll build
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
#  - sleep 5 # give xvfb some time to start

script:
#  - ./node_modules/karma/bin/karma start karma.conf.js
#  - htmlproof ./_site --verbose --href-ignore "#" --disable-external --file-ignore './_site/node_modules/*'
#  - jekyll serve &
#  - sleep 3 # give jekyll some time to start
  - galen test tests/galen/all.test --htmlreport tests/galen/reports/all

after_script:
  - rake travis:deploy --trace --verbose
