language: node_js, ruby
node_js:
  - "4.1"
rvm: 2.1

before_install:
        - npm install
        - npm install -g galenframework-cli
        - gem install jekyll
        - jekyll build

        
        - sh -e /etc/init.d/xvfb start
cache:
  directories :
    - node_modules

notifications:
  email:
    on_success: never
    on_failure: never
    email: false
