language: node_js
node_js:
  - "4.1"

before_install:
    - npm install
    - npm install -g galenframework-cli
    - npm test
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start

cache:
  directories :
    -node_modules

notifications:
  slack:
    on_success: never
    on_failure: never
    email: false
