language: node_js
node_js:
  - "4.1"

before_install:
    - npm install
    - npm install -g galenframework-cli
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - npm test

cache:
  directories :
    -node_modules

notifications:
  email:
    on_success: never
    on_failure: never
    email: false
