language: node_js
node_js:
  - "4.1"

before_install:
        - rvm install 2.1.5
        - npm install
        - npm install -g galenframework-cli
        - gem install jekyll
        - jekyll build


        - sh -e /etc/init.d/xvfb start
cache:
  directories :
    - node_modules

notifications:
    email: false

# whitelist
  branches:
    only:
     - master
     - gh-pages
     
# blacklist
branches:
  except:
    - legacy
    - experimenta
