language: node_js, ruby
node_js:
  - "4.1"
rvm: 2.1

raw: /travis/build/akmil/blogTestGalen/_site/index.html

before_install:
    - npm install
    - npm install -g galenframework-cli
    - gem install jekyll
    - jekyll build
    - jekyll serve &
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - npm test

cache:
  directories :
    - node_modules
    - bundler

notifications:
  email:
    on_success: never
    on_failure: never
    email: false
