language: node_js
node_js:
  - "4.1"

before_install:
  - sudo apt-get install openjdk-7-jdk
  - apt-get autoremove
  - java -version
  - mvn -version
  - phantomjs --version
  - npm install -g galenframework-cli
  - npm install -g grunt-cli
